#!/usr/bin/expect

set timeout 10
set host [lindex $argv 0]
set port [lindex $argv 1]

spawn telnet $host $port
expect "Connected to $host\."
send "GET / HTTP/1\.0\r\r"
expect "Connection closed by foreign host\."
close
     

